name: ci

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  schedule:
    - cron: '25 16 * * 1' # Schedule at 16:25 UTC on Mondays, which is midday in EST

jobs:
  Test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.8', '3.9', '3.10', '3.11']
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Check
        shell: bash
        run: |
          python3 -m pip install --upgrade pip wheel
          pip3 install -e .[full]
          PYTHONHASHSEED=0 TEST_WORD_EMBEDDINGS=bert,elmo python3 -m unittest discover -v tests
